# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sauron <sauron@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/17 09:18:03 by sauron            #+#    #+#              #
#    Updated: 2024/09/17 09:24:54 by sauron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = server.c client.c
OBJ = $(SRC:.c=.o)

CC = cc
CFLAGS = -Wall -Wextra -Werror

all: server client

bonus: server client

server: server.o libft
		$(CC) -o $@ $< -Llibft -Llibft

client: client.o libft
		$(CC) -o $@ $< -Llibft -Llibft

%.o: %.c
	$(CC) -c $(CFLAGS) $?

libft:
	make -C libft

clean:
	rm -f $(OBJ)
	make -C libft clean
	
fclean: clean
	rm -f server client libft/libft.a

re: fclean all

.PHONY: all bonus libft clean fclean re