# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    MakeFile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: sauron <sauron@student.42.fr>              +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/09/17 09:18:03 by sauron            #+#    #+#              #
#    Updated: 2024/09/17 09:44:37 by sauron           ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRC = server.c client.c
OBJ = $(SRC:.c=.o)

CC = cc
CFLAGS = -Wall -Wextra -Werror -Wno-unused-function

LIBFT_DIR = libft
LIBFT = $(LIBFT_DIR)/libft.a
LIBFT_INC = -I$(LIBFT_DIR)
LIBFT_LINK = -L$(LIBFT_DIR) -lft

all: server client

bonus: all

server: server.o $(LIBFT)
		$(CC) $(CFLAGS) -o $@ server.o $(LIBFT_LINK)

client: client.o $(LIBFT)
		$(CC) $(CFLAGS) -o $@ client.o $(LIBFT_LINK)

%.o: %.c
		$(CC) $(CFLAGS) $(LIBFT_INC) -c $< -o $@

$(LIBFT):
		make -C $(LIBFT_DIR)

clean:
		rm -f $(OBJ)
		make -C $(LIBFT_DIR) clean
	
fclean: clean
		rm -f server client
		make -C $(LIBFT_DIR) fclean

re: fclean all

.PHONY: all bonus clean fclean re
